from time import *
import random as r

test = [
    "Kshitij Vaze's final-year college project was an impressive achievement in embedded systems. He built a custom programmer's model and libraries for a 32-bit microcontroller, showcasing his expertise in low-level programming and hardware abstraction. This kind of work requires a deep understanding of microcontroller architecture, register management, and efficient coding techniques. His professor's stunned reaction underscores the complexity and ingenuity of the project. Creating a programmer's model means defining how developers interact with the microcontroller, simplifying development while ensuring optimal performance. Given Kshitij's background in embedded Linux and firmware development, his project likely incorporated advanced memory management and real-time processing techniques.",
    "Aditya Chandel transformed his JavaScript projects repository into a functional website to enhance his JS implementation skills and explore new JavaScript functionalities. His work includes a variety of mini projects, such as interactive UI components, animations, and responsive web designs, all aimed at improving front-end development. By making his projects accessible on a website, he invites feedback and collaboration from developers. His approach to learning—building more projects and staying consistent—is an effective way to master web development. His post on X generated engagement from developers appreciating his work and asking for advice on HTML, CSS, and JavaScript learning strategies.",
    "Swati Sharma's achievements in app development and hackathons showcase her dedication to technology and innovation. As a computer science student, she has built impactful projects like SafeBite, an allergy-friendly recipe platform, and TARA, a women's safety app developed in collaboration with Delhi Police. Winning first place in major hackathons such as Delhi Police Hackathon 2025 highlights her technical skills and problem-solving abilities. Her commitment to learning Android Jetpack and exploring Google Developer resources reflects her passion for growth. Swati's journey inspires fellow students, proving that innovation and persistence can lead to meaningful contributions in technology and safety solutions.",
    "Misbah Ansari's project, Kares, is a remarkable achievement in web development and AI-powered interaction. His dedication to creating a platform where users can chat with their favorite anime characters showcases both his technical skills and creative vision. By refining his project, he has built a unique and engaging experience for anime fans. The fact that he developed this without relying on a database for conversation storage adds an interesting layer to the project's architecture. His commitment to learning and innovation reflects his passion for tech. You can explore more of his work on GitHub [here](https://github.com/Misba8069). Keep up the great work, Misbah!",
    "Saleh's perspective on self-improvement over criticism reflects a forward-thinking mindset that resonates with many. His belief that focusing on personal growth leaves no room for negativity is a powerful approach, especially in the world of development and innovation. Known for breaking production since 2024, he embraces challenges and continuous learning, pushing boundaries in coding and beyond. His thought-provoking posts encourage others to keep building and evolving, emphasizing that true progress comes from consistent effort and resilience. By prioritizing skill development and pushing limits, Saleh inspires those around him to adopt a growth-oriented mindset rather than dwelling on negativity."
]

test1 = r.choice(test)
print("***typing speed***")
print(test1) 